---
  n_rnn: 1
  dim: 1024
  learn_h0: True
  q_levels: 256
  seq_len: 1024
  weight_norm: True
  batch_size: 128
  val_frac: 0.1
  test_frac: 0.1

  # training parameters
  keep_old_checkpoints: False
  datasets_path: datasets
  results_path: results
  epoch_limit: 1000
  resume: True
  sample_rate: 16000
  n_samples: 1
  sample_length:  128000
  sampling_temperature: 0.9 
  loss_smoothing: 0.99
  cuda: False
  comet_key: null
  frame_sizes:
    - 32
    - 4
